### ISSUE TITLE
Add website link 

### ISSUE THREAD

**Issue by AbbeyIT** [EliasPereyra/my-portfolio#1]
Add the website link in the documentation for your project document to be accessible.

**Comment by EliasPereyra** [comment]
Yes, sorry I forgot to put it. I'll do it in a second.

**Comment by AbbeyIT** [comment]
@EliasPereyra The link is not working

**Comment by EliasPereyra** [comment]
Sorry again, I typed so fast that I forgot a /. Now is working.

**Comment by AbbeyIT** [comment]
No need to be sorry. Everyone just helping here.

**Comment by EliasPereyra** [comment]
Yeah, thank you for your support
